Reading_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('user.urls', namespace='user')),
    path('book/', include('book.urls', namespace='book'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = []

main/urls.py
from django.urls import path
from .views import index

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
]

user/urls.py
from django.urls import path
from .views import sign_up, Login, Logout, activate

app_name = 'user'
urlpatterns = [
    path('sign_up', sign_up, name='sign up'),
    path('login', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('activate/<uidb64>/<token>', activate, name='activate')
]

book/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

user/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class Reader(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email adress'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now())

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

user/forms.py
from django import forms
from django.core.exceptions import ValidationError

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from . models import Reader


class ReaderCreationForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def email_clean(self):
        email = self.cleaned_data['email'].lower()
        new = Reader.objects.filter(email=email)
        if new.count():
            raise ValidationError('Email already exists')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
        return password2

    def save(self, commit=True):
        reader = Reader.objects.create_user(self.cleaned_data['email'],
                                            self.cleaned_data['password2'])
        return reader

    class Meta:
        model = Reader
        fields = ('email', 'password1', 'password2')


class ReaderChangeForm(UserChangeForm):
    class Meta:
        model = Reader
        fields = ('email',)


class ReaderLogInForm(AuthenticationForm):
    pass

book/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')

user/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import FormView
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
# from django.utils.decorators import

from .tokens import account_activation_token
from .forms import ReaderCreationForm
from .email_server import send

class Login(FormView):
    form_class = AuthenticationForm
    success_url = '/'
    template_name = 'user/login.html'

    def form_valid(self, form):
        self.reader = form.get_user()
        login(self.request, self.reader)
        return super(Login, self).form_valid(form)

    def form_invalid(self, form):
        return super(Login, self).form_invalid(form)


class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('/')


# @user_not_authenticated
def sign_up(request):
    if request.method == 'POST':
        form = ReaderCreationForm(request.POST)
        if form.is_valid():
            reader = form.save(commit=False)
            reader.is_active = False
            reader.save()

            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('user/activate_account.html', {
                'user': reader.email,
                'domain': get_current_site(request).domain,
                'uid': urlsafe_base64_encode(force_bytes(reader.pk)),
                'token': account_activation_token.make_token(reader),
                'protocol': 'https' if request.is_secure() else 'http'
            })
            print(message)
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            print("EmailMessage:", email)
            if email.send():
                print('Good')

            messages.success(request, f'Account for {email} was created!')
            # activate_email(request, reader, form.cleaned_data.get('email'))
            return redirect('/')
        else:
            return render(request, 'user/sign_up.html', {'form': form})
    else:
        print('Method GET')
        form = ReaderCreationForm()
        return render(request, 'user/sign_up.html', {'form': form})


def activate_email(request, user, to_email):
    mail_subject = 'Activate your account.'
    message = render_to_string('user/activate_account.html', {
        'user': user.email,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    # email = EmailMessage(mail_subject, message, to=[to_email])
    send(mail_subject, message, [to_email])
    # if email.send():
    messages.success(request, f'Dear <b>{to_email.split("@")[0]}</b, please go to your email <b>{to_email}</b> inbox and verify your account.'
                              f' <b>Note:</b> Check your spam folder.')
    # else:
    #     messages.error(request, f'Problem sending confirmation email to {to_email}, check if you typed it correctly.')


def activate(request, uidb64, token):
    return redirect('home')

Reading_tracker/user/templates/user/sign_in.html
{% extends 'main/base.html' %}

{% block content %}
<div class="log_in">
    {% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <h1>Sign in here </h1>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="Sign in"></td>
            </tr>
        </table>
    </form>
</div>
{% endblock content %}

book/templates/book/book review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

book/templates/book/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="book">
  <canvas id="pageflip-canvas"></canvas>
  <div id="pages">
    <section>
      <div></div>
    </section>
  </div>
</div>
</body>
</html>

book/templates/book/book_shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

book/templates/book/my_library.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock content %}
</body>
</html>

main/templates/main/contact_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Home page</h1>
{% if user.is_authenticated %}
    <a href="{% url 'user:logout' %}">Выйти</a> {{ user.email }}
{% else %}
    <a href="{% url 'user:login' %}">Войти</a> <br>
{% endif %}
{% endblock content %}

user/templates/user/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

user/templates/user/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

user/templates/user/login.html
{% extends 'main/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container py-5">
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="{% url 'user:sign up' %}">Create an account</a>.</p>
</div>
{% endblock content %}

user/templates/user/sign_up.html
{% extends 'main/base.html' %}

{% block content %}
<div class="sign_up">
    {% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <h1>Sign up here </h1>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="Sign up"></td>
            </tr>
        </table>
    </form>
</div>
{% endblock content %}

user/templates/user/tracker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>